// Optics is a namespace isolating all business logic relating to the behavior of light and other EM radiation
// This was written so I could decouple academic concerns (like how to model something mathematically) from architectural concerns (like how a model is represented through classes)
// All functions within the namespace are static and have no side effects
// The only data structures allowed are rasters and grid objects

var Optics = (function() {
	var Optics = {};


	// TODO: figure out where to put this between OrbitalMechanics and AtmosphereModeling
	// maybe another namespace, like "Thermodynamics"? "PhysicsModeling"?
	var STEPHAN_BOLTZMANN_CONSTANT = 5.670373e-11; // kW/m^2 per K^4

	// TODO: figure out where to put above function
	// maybe another namespace: "Heliosphere"? "StellarModeling" "Optics" ?
	OrbitalMechanics.SOLAR_LUMINOSITY = 3.828e23 // kiloWatts
	
	// This calculates the intensity of incident radiation (in kiloWatts/m^2) that's felt by the surface of an object.
	// The function considers the following:
	//  * the distance to the light (the "Inverse Square Law")
	//  * the occlusion of light by object itself
	//  * the angle at which the light hits ("Lambert's Law")
	Optics.incident_radiation = function(
			// This is a vector raster indicating the surface normal of an object
			surface_normal,
			// This is a vector indicating the objects's offset from the light source
			light_offset, 
			// total power output of light source in all directions, in kiloWatts
			luminosity,
			// Float32Raster that stores results
			result
		) {
		result = result || Float32Raster(pos.grid);

		// this is a vector of the sun's geocentric position 
		var light_direction = Vector(
			-light_offset.x, 
			-light_offset.y, 
			-light_offset.z
		);

		// use cosine similarity to find cosine of solar zenith angle 
		VectorField.vector_similarity 	(geocentric_ecliptic_pos_field, light_direction, 	result);

		// obscure light where it is occluded by the object
		Float32RasterInterpolation.clamp(result, 0, 1, 										result);

		var light_distance = Vector.magnitude(
			light_offset.x,
			light_offset.y,
			light_offset.z
		);
		// intensity of stellar insolation, in kiloWatts/m^2
		// this is the power generated by a 100% efficient, 1 m^2 solar panel that's directly facing the sun
		var intensity = luminosity / ( 4 * Math.PI * light_distance * light_distance );

		ScalarField.mult_scalar			( result, intensity, 								result );

		return result;
	}


	return Optics;
})();
