var Units = {};

Units.KG_IN_TONS = 1000.;

Units.SOLAR_MASS = 2e30 // kg
Units.SOLAR_RADIUS = 695.7e6 // meters
Units.SOLAR_LUMINOSITY = 3.828e26 // watts

Units.EARTH_MASS = 6367e3; // kg
Units.EARTH_RADIUS = 6.367e6; // meters
Units.ASTRONOMICAL_UNIT = 149597870700; // meters
Units.SECONDS_IN_MINUTE = 60;
Units.SECONDS_IN_HOUR = Units.SECONDS_IN_MINUTE*60;
Units.SECONDS_IN_DAY = Units.SECONDS_IN_HOUR*24;
Units.SECONDS_IN_MONTH = Units.SECONDS_IN_DAY*31;
Units.SECONDS_IN_YEAR = Units.SECONDS_IN_DAY*365.25;
Units.SECONDS_IN_MEGAYEAR = Units.SECONDS_IN_YEAR*1e6;

Units.JUPITER_MASS = 1.898e27; // kg
Units.JUPITER_RADIUS = 71e6; // meters
